#!/bin/sh

# código para poder recuperar la opción restaurar sistema en las netbooks de Conectar Igualdad.

exec tail -n +3 $0
menuentry 'Restaurar sistemas' {
insmod ext3
set root='(hd0,5)'
linux /live-hd/vmlinuz boot=live live-config union=aufs live-media-path=/live-hd toram bootfrom=/dev/sda5 noprompt noprompt ocs_live_run="/live/image/script-restore" ocs_live_extra_param="" ocs_live_keymap="NONE" ocs_live_batch="yes" ocs_lang="es_ES.UTF-8" nolocales
initrd /live-hd/initrd.img
}
### END /etc/grub.d/39_custom ### 
