#!/bin/bash

# screenfetch_huayra: Script para instalar automaticamente ScreenFetch en Huayra GNU/Linux.
# Autor: Julio A. GÓMEZ, Melincué, Santa Fe, Argentina.

# Contacto a: gomez-ja@hotmail.com.ar

# Actualizado: 

# Comentarios:
#             Se espera que funcione correctamente, en Huayra GNU/Linux, con entorno Mate activo.
#             Se probó en version: 2.2 (32bits).

# Uso:
#     Con permisos de ejecución se debe ejecutar el script en una terminal y se instalará todo automáticamente.
#     Se abre una terminal y se usa el comando: screenfetch
#     Disfrutar.

# Edición en GitHub: 

# Debate en Foros:  

# Licencia: General Public License Version 3 (GPL v3) (en inglés, válida legalmente)
#           http://www.gnu.org/licenses/gpl.txt
#           Licencia Pública General de GNU Versión 3 (en Español)
#           (Traducciones NO oficiales, para facilitar interpretación)
#           http://gugs.sindominio.net/licencias/

echo instalador de screenfetch

echo ...dentro 5 seg se inicia el script, o cierre la terminal

sleep 5s

cd /usr/bin 

sudo wget -c https://raw.github.com/KittyKatt/screenFetch/master/screenfetch-dev -O screenfetch

sudo chmod +x screenfetch
